version: '3.3'

services:
  # app:
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - db
  #   environment:
  #     - DATABASE_URL=postgresql://admin:admin@db:5432/db_crypto-hold
  #   networks:
  #     - postgres-compose-network

  db:
    image: postgres
    container_name: lass-db
    restart: always
    command: postgres -c 'max_connections=1000'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=db_lass
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./data:/data
    networks:
      - postgres-compose-network

  pgadmin-compose:
    image: dpage/pgadmin4
    container_name: admin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge
